import * as fs from 'fs';
import * as path from 'path';
import { DatabaseCleaner } from './utils/database-cleaner';

// Load env vars generated by global setup
const envPath = path.join(__dirname, '.e2e-env.json');
if (fs.existsSync(envPath)) {
  const envConfig = JSON.parse(fs.readFileSync(envPath, 'utf-8')) as Record<
    string,
    string
  >;
  for (const k in envConfig) {
    process.env[k] = envConfig[k];
  }
}

afterEach(async () => {
  await DatabaseCleaner.clean();
});

afterAll(async () => {
  await DatabaseCleaner.close();
});
