import * as fs from 'fs';
import * as path from 'path';

// Load env vars generated by global setup
const envPath = path.join(__dirname, '.e2e-env.json');

if (!fs.existsSync(envPath)) {
  throw new Error(
    `E2E environment file not found at "${envPath}". Ensure global setup has created ".e2e-env.json".`,
  );
}

let envConfigRaw: string;
try {
  envConfigRaw = fs.readFileSync(envPath, 'utf-8');
} catch (err) {
  throw new Error(
    `Failed to read E2E environment file at "${envPath}": ${(err as Error).message}`,
  );
}

let envConfig: Record<string, string>;
try {
  envConfig = JSON.parse(envConfigRaw) as Record<string, string>;
} catch (err) {
  throw new Error(
    `Failed to parse E2E environment file at "${envPath}" as JSON: ${(err as Error).message}`,
  );
}

for (const k in envConfig) {
  process.env[k] = envConfig[k];
}

const requiredEnvVars = ['DATABASE_URL'];
for (const key of requiredEnvVars) {
  const value = process.env[key];
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(
      `Required environment variable "${key}" is missing or empty in the E2E environment configuration.`,
    );
  }
}
